name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: git config --global user.email "lip@lip.net.ua"
      - run: git config --global user.name "aspel"
      - run: npm version patch -m "Upgrade to [%s]"
      - run: npm install vsce
      - run: vsce package